### ISSUE TITLE
Formatted headers show up with HTML tags in box "active columns"

### ISSUE THREAD

**Issue by SeparateReality** [moderntribe/advanced-post-manager#20]
This happens for instance with tribe events calendar and woocommerce even more.

The function output_form() uses esc_htm() to echo the button text and the dropdown text.
It would be great to just change it to wp_strip_all_tags().

in tribe-columns.class.php I changed line 149 from
`echo esc_html( $headers[ $v ] );`
to
`echo wp_strip_all_tags($headers[ $v ]);`

and line 167 from
`echo '<option value="' . esc_attr( $key ) . '">' . esc_html( $name ) . '</option>';`
to
`echo '<option value="' . esc_attr( $key ) . '">' . wp_strip_all_tags( $name ) . '</option>';`

And by the way: Thanks for the great work!

![image](https://cloud.githubusercontent.com/assets/13707244/12529381/ff3df336-c1b3-11e5-9f14-5aef2328e61a.png)

**Comment by SeparateReality** [comment]
The plugin is really nice.
But why do you not change those two lines of code to make it even nicer.
The user experience is really awful and we change those two lines after every update...
I guess there are many people out there using woocommerce and having the same issue.
It is still the same file and the same lines as mentioned above.
Thanks a lot! We really appreciate the great work together with Tickets Plus and Calendar Pro! 

![image](https://cloud.githubusercontent.com/assets/13707244/16302241/4db57968-394a-11e6-8463-b5d133b938a6.png)

**Comment by zbtirrell** [comment]
Thanks for this bug report, it is definitely appreciated. We don't use GitHub Issues and had forgotten to disable it here, which is why we missed your original report. I have since ticketed this in our internal tracking system and can assure you we'll fix this before our next APM release.

I'm going to close out this ticket though, in the future, we'd be happy to take bug reports in the WordPress.org support forums - https://wordpress.org/support/plugin/advanced-post-manager
